// <auto-generated />
using System;
using IndustrieDashboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrieDashboard.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008005925_IdentitaetUndZeugenpfad")]
    partial class IdentitaetUndZeugenpfad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("IndustrieDashboard.Core.Models.AuditLogEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlterWert")
                        .HasColumnType("TEXT");

                    b.Property<string>("Begruendung")
                        .HasColumnType("TEXT");

                    b.Property<string>("Benutzer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerKennung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GegengezeichnetVon")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kategorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NeuerWert")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Zeitstempel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zielobjekt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogEintraege");
                });

            modelBuilder.Entity("IndustrieDashboard.Core.Models.KontrolleingriffAnforderung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AngefordertAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AngefordertVon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AngefordertVonKennung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AusnahmeGrund")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FreigegebenAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreigegebenVon")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreigegebenVonKennung")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaschineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZeugeAnzeigename")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ZeugeBestaetigtAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZeugeKennung")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KontrolleingriffAnforderungen");
                });

            modelBuilder.Entity("IndustrieDashboard.Core.Models.Maschine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AktuellerWert")
                        .HasColumnType("REAL");

                    b.Property<string>("FeldbusKennung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LetzteAktualisierung")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Standort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Maschinen");
                });

            modelBuilder.Entity("IndustrieDashboard.Core.Models.Maschinenmesswert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kennwert")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaschineId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Wert")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Zeitstempel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaschineId");

                    b.ToTable("Maschinenmesswerte");
                });

            modelBuilder.Entity("IndustrieDashboard.Core.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personalnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualifikation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("IndustrieDashboard.Core.Models.Schicht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Beginn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Ende")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schichten");
                });

            modelBuilder.Entity("MitarbeiterSchicht", b =>
                {
                    b.Property<int>("MitarbeiterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchichtId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MitarbeiterId", "SchichtId");

                    b.HasIndex("SchichtId");

                    b.ToTable("MitarbeiterSchicht");
                });

            modelBuilder.Entity("IndustrieDashboard.Core.Models.Maschinenmesswert", b =>
                {
                    b.HasOne("IndustrieDashboard.Core.Models.Maschine", "Maschine")
                        .WithMany("Messwerte")
                        .HasForeignKey("MaschineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maschine");
                });

            modelBuilder.Entity("MitarbeiterSchicht", b =>
                {
                    b.HasOne("IndustrieDashboard.Core.Models.Mitarbeiter", null)
                        .WithMany()
                        .HasForeignKey("MitarbeiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndustrieDashboard.Core.Models.Schicht", null)
                        .WithMany()
                        .HasForeignKey("SchichtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IndustrieDashboard.Core.Models.Maschine", b =>
                {
                    b.Navigation("Messwerte");
                });
#pragma warning restore 612, 618
        }
    }
}
